version: b{build}

environment:
  nodejs_version: 12
  GH_TOKEN:
    secure: febq/MqfzS/3JfchQVtlarZApEi80xRea6Z5qvUTYeb1vH8ByxIXqavTh6DIo53/

image:
  - Visual Studio 2019

platform: Any CPU

only_commits:
  files:
    - desktop/

cache:
  - desktop\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm bootstrap
  - cd desktop
  - npm add jquery
  - npm add popper.js

build_script:
  - npm run build:all
  - npm run package:win
