version: b{build}

environment:
  nodejs_version: "8"
  GH_TOKEN:
    secure: febq/MqfzS/3JfchQVtlarZApEi80xRea6Z5qvUTYeb1vH8ByxIXqavTh6DIo53/

os: unstable

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm add jquery
  - npm add popper.js

build_script:
  - npm run build
  - npm run package-win

notifications:
  - provider: Slack
    auth_token:
      secure: 8igb/45j7jFO/0zlLOXgvxk6AQzx68GVkMrY17G8sDhMXkofJ3jnqF6qT204DLdI7RrL5rNUt9WspyagZrzL/Gt3SVaenCd6xx7S8VQz/sk=
    channel: '#builds'
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
