name: build-desktop
on:
  push:
    paths:
    - "core/**"
    - "desktop/**"
    - ".github/workflows/build-desktop.yml"
jobs:
  build-desktop:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - uses: c-hive/gha-npm-cache@v1
    - run: npm i
    - run: npm run bootstrap
    - run: npm run build
      working-directory: core
    - run: npm run build:all
      working-directory: desktop
    - run: npm run package:mac
      if: runner.os == 'macOS'
      env:
        CSC_LINK: ${{ secrets.MAC_CERT }}
        CSC_KEY_PASSWORD: ${{ secrets.MAC_CERT_PW }}
      working-directory: desktop
    - run: npm run package:win
      if: runner.os == 'Windows'
      env:
        CSC_LINK: ${{ secrets.WIN_CERT }}
        CSC_KEY_PASSWORD: ${{ secrets.WIN_CERT_PW }}
      working-directory: desktop
    - run: npm run package:lnx
      if: runner.os == 'Linux'
      working-directory: desktop
