name: build-desktop
on:
  push:
    paths:
    - "core/**"
    - "desktop/**"
    - ".github/workflows/build-desktop.yml"
jobs:
  build-desktop:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            os-short: lnx
          - os: macos-latest
            os-short: mac
          - os: windows-latest
            os-short: win
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm i
    - run: npm run bootstrap
    - run: npm run build
      working-directory: core
    - run: npm run build:all
      working-directory: desktop
    - run: npm run package:${{ matrix.os_short }}
      working-directory: desktop
