language: node_js

node_js:
  - lts/*

matrix:
  include:
  - os: osx
    osx_image: xcode10.2
  - os: linux

cache:
  directories:
  - "$HOME/.electron"
  - "$HOME/.cache"
  - "$HOME/Library/Caches/electron"
  - "$HOME/Library/Caches/electron-builder"

addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils

before_install:
- export CHROME_BIN=chromium-browser

install:
- npm install --force
- npm add jquery
- npm add popper.js

script:
- npm rebuild node-sass
- npm run build:all
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then npm run package:mac; else npm run package:lnx; fi

env:
  global:
    secure: Y5VQzk+Ucu3NU3KWuT2ClTT7SRWU/O20mi6ENIbWADNnzjUam7cKugWLnXkOEIKbqqc4hZuvRoixc9VXTtf9ihkowjsHHoyptpbDp0jOiwPfjpv/2HTuDutgZaiIQ3fjZC4JfLSSsxTn+k7vbEcffoGndGNajO0B/O3ZxQJ8kwt+wkAfwumpCPXjn9oaXFoMXxvfXBAypn14syQrNgiYj4CJzTmZyPN+HvsEiTErR+Gek5aapOUZ0eq6KBbqfHvO3fn1HrFZnwRPdt5Jcs6WHqTERkmDf1H+4PDEA9NeWAzRbo2Qdpll4gLMDBTu27UQxpilToz4SGWgHadnhc90K5cW1qFFC6fIIjEtNt/wFstWGimQAhWJYLi2L6/C1HmhdnqhGMbO5GCOrRQMeKI+iRDw4XSjBej3oKR6VePQZd7iolLxX5anCXsJacEnLbZ9mn6t31/svZh+TV7enMtg25d9HDtApR4kcRHXf71ihZ1XSE+9EW12xAWYHdDmpUCnl80n7Se6GGOjwNqsAdzzr4rxdWUXb8Ai35FM8L/dQ619ufbBZzYT4IhukMmebDizMKJT5yiHx3GBuV2KCRzm1e1HeCfcjLknjHeoUlrsBB80pWkGjlXB5o5YhqlTqHhjKA+nXfY/T99xKWtkPEt4XXQCjsYb72GJw+DppVL67EY=
